---
- name: Run few Linux commands
  hosts: localhost
  gather_facts: false
  become: false
  tasks:
    - name: Get OS version
      ansible.builtin.shell:
        cmd: cat /etc/os-release
      register: os-release
      no_log: false

    - debug: var=os-release
    
    - name: Get OS hostname
      ansible.builtin.shell:
        cmd: hostname
      no_log: false
    
    - name: List log directory
      ansible.builtin.shell:
        cmd: ls -l 
        chdir: /var/log
      no_log: false